---
kind: pipeline
type: docker
name: Build docker image

steps:
  - name: Build
    image: alpinelinux/docker-cli
    volumes:
    - name: docker_sock
      path: /var/run/docker.sock
    commands: 
    - docker build -t flaskapp:$DRONE_BUILD_NUMBER .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push flaskapp:$DRONE_BUILD_NUMBER

volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock
