---
kind: pipeline
name: build-docker-image
type: exec
steps:
  - name: build
    commands:
      - docker build -t flaskapp:$DRONE_BUILD_NUMBER .
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker push flaskapp:$DRONE_BUILD_NUMBER
